export let  arrOfApplication = 
  [
    {
      id:1,
      AppName:"PEP",
      imageUrl:"./images/normal.jpg",
      rating:3,
      CreatedBy:"",
      AppDescription:"",
      environments:[1,2,3]
    },
    {
      id:112,
      AppName:"PPM",
      imageUrl:"./images/normal.jpg",
      rating:3,
      CreatedBy:"",
      AppDescription:"",
      environments:[1,3,4]
    },
    {
      id:2,
      AppName:"Salesforce",
      imageUrl:"./images/normal.jpg",
      rating:4,CreatedBy:"",
      AppDescription:"",
      environments:[1,3,4]
    },
    {
      id:3,
      AppName:"Dotnet",
      imageUrl:"./images/normal.jpg",
      rating:4,CreatedBy:"",
      AppDescription:"",
      environments:[1,2,5]
    },
    {
      id:4,
      AppName:"Java",
      imageUrl:"./images/normal.jpg",
      rating:3,CreatedBy:"",
      AppDescription:"",
      environments:[1,3,2]
    },
    {
      id:5,
        AppName:"Azure",
        imageUrl:"./images/normal.jpg",
        rating:2,CreatedBy:"",
      AppDescription:"",
      environments:[1,2,3]
    },
    {
      id:6,
      AppName:"Infor",
      imageUrl:"./images/normal.jpg",
      rating:5,CreatedBy:"",
      AppDescription:"",
      environments:[1,4,5]
    },
    {
      id:7,
      AppName:"SAP",
      imageUrl:"./images/normal.jpg",
      rating:5,CreatedBy:"",
      AppDescription:"",
      environments:[1]
    },
    {
      id:8,
      AppName:"ASP.NET",
      imageUrl:"./images/normal.jpg",
      rating:5,CreatedBy:"",
      AppDescription:"",
      environments:[3,4,5]
    },
    {
      id:9,
      AppName:"ASP.NET Core",
      imageUrl:"./images/normal.jpg",
      rating:5,CreatedBy:"",
      AppDescription:"",
      environments:[1,2]
    },
    {
      id:10,
      AppName:"Spring",
      imageUrl:"./images/normal.jpg",
      rating:5,CreatedBy:"",
      AppDescription:"",
      environments:[1,5]
    },
    {
      id:11,
      AppName:"Spring Boot",
      imageUrl:"./images/normal.jpg",
      rating:1,CreatedBy:"",
      AppDescription:"",
      environments:[2,4]
    },
    {
      id:12,
      AppName:"C#",
      imageUrl:"./images/normal.jpg",
      rating:1,CreatedBy:"",
      AppDescription:"",
      environments:[1,4]
    },
    {
      id:13,
      AppName:"MuleSoft",
      imageUrl:"./images/normal.jpg",
      rating:1,
      CreatedBy:"",
      AppDescription:"",
      environments:[1,5]
    },
    {
      id:14,
      AppName:"Data Power",
      imageUrl:"./images/normal.jpg",
      rating:5,CreatedBy:"",
      AppDescription:"",
      environments:[1,2]
    },
    {
      id:15,
      AppName:"ODM",
      imageUrl:"./images/normal.jpg",
      rating:5,CreatedBy:"",
      AppDescription:"",
      environments:[4,5]
    },
    {
      id:16,
      AppName:"UI Path",
      imageUrl:"./images/normal.jpg",
      rating:5,CreatedBy:"",
      AppDescription:"",
      environments:[4,5]
    },
    {
      id:17,
      AppName:"Angular",
      imageUrl:"./images/normal.jpg",
      rating:4,CreatedBy:"",
      AppDescription:"",
      environments:[5]
    },
    {
      id:18,
      AppName:"React",
      imageUrl:"./images/normal.jpg",
      rating:4,CreatedBy:"",
      AppDescription:"",
      environments:[5]
    },
    {
      id:19,
      AppName:"Dell Boomi",
      imageUrl:"./images/normal.jpg",
      rating:1,CreatedBy:"",
      AppDescription:"",
      environments:[5]
    },
    {
      id:20,
      AppName:"Selenium",
      imageUrl:"./images/normal.jpg",
      rating:1,CreatedBy:"",
      AppDescription:"",
      environments:[5],
    },
  ];